dist: trusty
language: cpp
services: docker

stages:
  - test
  - osx

cache:
  directories:
    - $HOME/.ccache
    - $HOME/Library/Caches/Homebrew

compiler:
  - gcc
  - clang

env:
  global:
    - TRAVIS_CMAKE_GENERATOR="Ninja"
    - DEPS_BRANCH="master"
  matrix:
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="xenial"
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="xenial"
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="bionic"
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="bionic"

# ===================
# STAGE: test (linux)
# ===================

# This step is shared with osx stage
before_install:
  - if [ "$TRAVIS_BRANCH" != "master" ] ; then export DEPS_BRANCH="devel" ; fi
  - if echo $TRAVIS_COMMIT_MESSAGE | grep -F -q "[ci master]" ; then export DEPS_BRANCH="master" ; fi
  - if echo $TRAVIS_COMMIT_MESSAGE | grep -F -q "[master ci]" ; then export DEPS_BRANCH="master" ; fi

before_script:
  - echo "Using $DEPS_BRANCH for dependencies"
  - >-
    if [ "$UBUNTU" = "xenial" ] ; then
      export DOCKER_IMAGE_NAME=robotology/robotology-tdd:gazebo8${DEPS_BRANCH}
    elif [ "$UBUNTU" = "bionic" ] ; then
      export DOCKER_IMAGE_NAME=robotology/robotology-tdd:gazebo9${DEPS_BRANCH}
    else
      travis_terminate 1
    fi
  - docker pull $DOCKER_IMAGE_NAME

script:
  - >-
    docker run -it \
      -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
      -v $HOME/.ccache:$HOME/.ccache \
      -w $TRAVIS_BUILD_DIR \
      --env-file .ci/env-file \
      $DOCKER_IMAGE_NAME \
      sh .ci/script.sh

# ==========
# STAGE: osx
# ==========

stage_osx:
  install: &osx_install
    # Setup the dependencies folder
    - export DEPS_INSTALL_PREFIX=$HOME/deps
    - export PATH=$PATH:$DEPS_INSTALL_PREFIX/bin
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DEPS_INSTALL_PREFIX/lib
    - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEPS_INSTALL_PREFIX
    - export CMAKE_BUILD_OPTIONS=""
    # Setup ccache
    - brew install ccache
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    # Install dependencies
    - brew install eigen ace tinyxml gsl
    - cd $TRAVIS_BUILD_DIR/.ci
    - ./install.sh || travis_terminate 1
  script: &osx_script
    - cd $TRAVIS_BUILD_DIR/.ci
    - ./script.sh

# ======================
# BUILD JOBS FROM STAGES
# ======================

jobs:
  include:
    # ---------
    # STAGE OSX
    # ---------
    - &osx_template
      stage: osx
      os: osx
      osx_image: xcode10
      before_install: skip
      install: *osx_install
      before_script: skip
      script: *osx_script
      after_failure: skip
      after_success: skip
      after_script: skip
      env:
        TRAVIS_CMAKE_GENERATOR="Xcode"
        TRAVIS_BUILD_TYPE="Debug"
    - <<: *osx_template
      compiler: clang
      env:
        TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
        TRAVIS_BUILD_TYPE="Debug"

# notifications:
#  email:
#    - whowantstobemantainedr@email.com
